---
AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EventBridge rule that triggers a Lambda function daily at 02:00 MST\

Parameters:
  CodeS3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda function code ZIP file
  CodeS3Key:
    Type: String
    Description: S3 key for the Lambda function code ZIP file (e.g., lambda.zip)

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  # Lambda Function
  ScrapeCrosswordsLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: ScrapeCrosswordsFunction
      Handler: index.lambda_handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref CodeS3Bucket
        S3Key: !Ref CodeS3Key
      Runtime: nodejs18.x
      Timeout: 60
      MemorySize: 128

  # EventBridge Rule
  DailyScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Triggers Lambda function daily at 02:00 MST
      ScheduleExpression: cron(0 9 * * ? *)
      State: ENABLED
      Targets:
        - Arn: !GetAtt ScrapeCrosswordsLambda.Arn
          Id: ScrapeCrosswordsLambdaTarget

  # Permission for EventBridge to invoke Lambda
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref ScrapeCrosswordsLambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DailyScheduleRule.Arn

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt DailyTaskLambda.Arn
  EventBridgeRuleArn:
    Description: ARN of the EventBridge rule
    Value: !GetAtt DailyScheduleRule.Arn